server:
  port: 8040

spring:
  application:
    name: user-service
  docker:
    compose:
      enabled: false
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      default_schema: users_service
      ddl-auto: none
      naming:
        physical-strategy:threads: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_query_cache: true
          auto_evict_collection_cache: true
          redisson:
            fallback: true
            config: redisson/redisson.yaml
            defaultCache:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 7200000 # in milliseconds
                max_idle_time: 7200000 # in milliseconds
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 10
  threads:
    virtual:
      enabled: true
  liquibase:
    default-schema: users_service
    contexts: default

logging:
  level:
    org:
      hibernate:
        SQL_SLOW: INFO
